stages:
  - coverage
  - docs

coverage:
  stage: coverage
  coverage: '/Statements.*?(\d+(?:\.\d+)?)/'
  only:
    - master
  script:
    - rm -rf package-lock.json
    - npm install
    - npm run coverage
    - ls
    - mkdir -p ${EE_REPORT}/${CI_PROJECT_PATH}/coverage/
    - mv coverage/lcov-report/* ${EE_REPORT}/${CI_PROJECT_PATH}/coverage/
    - ls ${EE_REPORT}/${CI_PROJECT_PATH}/coverage/
  artifacts:
    paths:
      - coverage/

docs:
  stage: docs
  only:
    - master
  script:
    - npm run docs:build
    - ls
    - mkdir -p ${EE_REPORT}/${CI_PROJECT_PATH}/docs/
    - mv docs/.vuepress/dist/* ${EE_REPORT}/${CI_PROJECT_PATH}/docs/
    - ls ${EE_REPORT}/${CI_PROJECT_PATH}/docs/
