language: node_js
cache:
    directories:
        - node_modules

node_js:
    - "10"
    - "8"

install:
    - npm install

script:
    - npm test
    - npm run coverage

# deploy:
#     provider: npm
#     email: $NPM_EMAIL
#     api_key: $NPM_API_KEY
#     skip_cleanup: true
#     on:
#         tags: true
#         node: "8"

# after_success:
#     - npm run coverage