language: node_js
cache:
  directories:
    - node_modules

node_js:
  - '10'
  - '8'

install:
  - npm install

script:
  - npm build
  - npm run coverage
  - npm run deploy

after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
# after_success:
#     - npm run coverage
